version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend
    networks:
      - solmate-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
    restart: always
    depends_on:
      - mongodb
    networks:
      - solmate-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - solmate-network
    command: --wiredTigerCacheSizeGB 1.5

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - solmate-network

networks:
  solmate-network:
    driver: bridge

volumes:
  mongodb_data:
