version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - solmate-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/solmate
      - JWT_SECRET=development_secret_key
      - SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
    depends_on:
      - mongodb
    networks:
      - solmate-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - solmate-network

networks:
  solmate-network:
    driver: bridge

volumes:
  mongodb_data:
